# .github/workflows/add_issues_to_project.yml

name: Add issues to project

on:
  issues:
    types:
      - opened
env:
  BUG_PROJECT: 
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/DusKong/projects/1/views/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}