# .github/workflows/add_issues_to_project.yml

name: Add issues to project

on:
  issues:
    types:
      - opened
      - closed
      - assigned
      - reopened
env:
  PROJECT_NAME: TEST
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/DusKong/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}